import type { Metadata } from 'next'

import '../globals.css'
import { isAuthenticated } from '@/src/auth/auth'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  if (!isAuthenticated()) {
    redirect('/auth/sign-in')
  }

  return <>{children}</>
}
