import type { Metadata } from 'next';

import '../globals.css';
import { isAuthenticated } from '@/src/auth/auth';
import { redirect } from 'next/navigation';
import Header from '@/src/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  teste,
}: Readonly<{
  children: React.ReactNode;
  teste: React.ReactNode;
}>) {
  if (!isAuthenticated()) {
    redirect('/auth/sign-in');
  }

  return (
    <div>
      {children}
      {teste}
    </div>
  );
}
