import '../globals.css'
import type { Metadata } from 'next'
import { isAuthenticated } from '@/src/auth/auth'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  sheet,
}: Readonly<{
  children: React.ReactNode
  sheet: React.ReactNode
}>) {
  if (!isAuthenticated()) {
    redirect('/auth/sign-in')
  }

  return (
    <div>
      {children}
      {sheet}
    </div>
  )
}
